# Generated by Django 3.2.6 on 2021-09-02 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(blank=True, max_length=200, null=True, verbose_name='工程名称')),
                ('inum', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('iprice', models.FloatField(blank=True, null=True, verbose_name='单价')),
                ('itotal', models.FloatField(blank=True, null=True, verbose_name='合计价格')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='项目名称')),
                ('oid', models.IntegerField(blank=True, null=True, verbose_name='机构名称')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(blank=True, max_length=200, null=True, verbose_name='机构名称')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=200, null=True, verbose_name='项目名称')),
                ('oid', models.IntegerField(blank=True, null=True, verbose_name='机构ID')),
            ],
        ),
    ]
