# Generated by Django 3.2.6 on 2021-09-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='oid',
            field=models.IntegerField(blank=True, null=True, verbose_name='机构ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='项目ID'),
        ),
    ]
