# Generated by Django 3.2.8 on 2021-10-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='合计价格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tcount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='含税费用'),
        ),
    ]
