# Generated by Django 3.2.6 on 2021-10-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20210902_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='idate',
            field=models.DateTimeField(default=None, verbose_name='项目日期'),
        ),
        migrations.AddField(
            model_name='item',
            name='imemo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='项目备注'),
        ),
        migrations.AddField(
            model_name='item',
            name='isUrgency',
            field=models.BooleanField(default=False, verbose_name='是否加急'),
        ),
        migrations.AddField(
            model_name='item',
            name='itaxi',
            field=models.IntegerField(blank=True, null=True, verbose_name='税率'),
        ),
        migrations.AddField(
            model_name='item',
            name='shipcount',
            field=models.FloatField(blank=True, null=True, verbose_name='运费'),
        ),
        migrations.AddField(
            model_name='item',
            name='tcount',
            field=models.FloatField(blank=True, null=True, verbose_name='含税费用'),
        ),
        migrations.AddField(
            model_name='item',
            name='toWhere',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='运送方式'),
        ),
    ]
