# Generated by Django 3.2.6 on 2021-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20211018_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itaxi',
            field=models.FloatField(default=0.13, null=True, verbose_name='税率'),
        ),
    ]
